### ISSUE TITLE
Private bitbucket repo?

### ISSUE THREAD

**Issue by JulianKingman** [CyCoreSystems/docker-meteor#10]
Is it possible to use this with a private bitbucket repo?

**Comment by Ulexus** [comment]
It should be, yes.  I haven't tried it, but you can use the `DEPLOY_KEY` environment variable to specify the path in which the script can find your private SSH key for the git connection.  This works fine with Github, but I would like to know if you run into any trouble with Bitbucket.

**Comment by JulianKingman** [comment]
What’s the best practice on where to put your key? I’d imaging it’s not very secure to put it in a public dropbox folder or something.

**Comment by Ulexus** [comment]
I put it in a directory on each host, and then bind-mount that into place when starting the container.  Again, that is done in the example unit file.

How you get it in the host is another thing, of course.  I use my private Ceph cluster, but you can also use a password-protected S3 or something.

Regardless, make sure it is not you primary key.  Make a special deployment key and give it read access only.

**Comment by Ulexus** [comment]
Closing this for cleanliness.  Please reopen if it doesn't work, for some reason.
