### ISSUE TITLE
Local packages 

### ISSUE THREAD

**Issue by sksourou** [CyCoreSystems/docker-meteor#13]
#Hi, how can i add local packages for my app who work with 
environment variable ? 

```error: unknown package in top-level dependencies: rolljee:getfoldersize
unknown package in top-level dependencies: rolljee:pkgcloud```

**Comment by Ulexus** [comment]
Local packages should work as long as they are in place.  Are yours not committed with your main source repository?  If not, you'll need to link in the packages as volumes.

**Comment by sksourou** [comment]
They're not ! How can i do for add my packages as volumes ? i add to my dockerfile ```VOLUME D:/meteor-packages``` but for my environment variable how can i found the way into the containair?
