### ISSUE TITLE
Docker help

### ISSUE THREAD

**Issue by scheung38** [CyCoreSystems/docker-meteor#18]
Hi 

Does docker pull meteor mean that my working IDE is in Win or Mac OSX, but the actual running and deployment of code to be in the Linux environment based on shared library?

**Comment by Ulexus** [comment]
I do not understand your question.

**Comment by scheung38** [comment]
I mean with this docker image, will I still be working in my Win environment because I have IDE license for Win only, but the actual source code will be deployed and shareable in Linux environment?

**Comment by Ulexus** [comment]
I don't use Windows, so I don't know if there is a way to share the live source with both this container and your IDE.  On Linux, it is trivial:  you just bind-mount the source in the tree.

That said, this container is designed with _deployment_ in mind, not really development.  Daniel Dent and Arunoda Susiripula (at least used to) have development-oriented containers for Meteor which may suit your use case better.  I'd be happy to add features or make a dev tag to make this easier... but I don't really know anything about the Windows-IDE-Docker setup.

**Comment by Ulexus** [comment]
Closing old issue...
