### ISSUE TITLE
How to set DEPLOY_KEY

### ISSUE THREAD

**Issue by Maxim-Filimonov** [CyCoreSystems/docker-meteor#2]
Do I need to build a Dockerfile on top of your container to use?
I'm trying to do:
```> docker run --rm -e REPO=<REPO> -e MONGO_URL=<MONGO_URL> -e DEPLOY_KEY=/Users/maxim/repos/frontend/docker_meteor ulexus/meteor
=> cp: cannot stat '/Users/maxim/repos/frontend/docker_meteor': No such file or directory
```
I have tried to set key permissions to 777 but that doesn't seem to help.

**Comment by Ulexus** [comment]
Make sure that the DEPLOY_KEY is available _inside_ the container.  If you are referencing an external file, you'll want to pull it in with `-v`.  Something like:
`docker run --rm -e REPO= -e MONGO_URL= -e DEPLOY_KEY=/docker_meteor -v /Users/maxim/repos/frontend/docker_meteor:/docker_meteor ulexus/meteor`

**Comment by Ulexus** [comment]
Please reopen if this isn't your issue; sorry about that
