### ISSUE TITLE
Unable to connect mongo

### ISSUE THREAD

**Issue by rwatts3** [CyCoreSystems/docker-meteor#23]
Greetings I am unable to connect to a self hosted mongo instance.  

It seems the imsge is forcing me to use port 27017 I. The url when it true to rub the application.  My instance of mongo does not contain a port.  Its a direct url with the oath of the database.  

Do you have any suggestions to get around this ?

**Comment by Ulexus** [comment]
I didn't know MongoDB had a UNIX socket connection method, but as long as Meteor can use that method, this image should support it.  It makes no assumptions on `MONGO_URL`.  Just set that to whatever the path should be, and you should be fine; so far as I am aware, that is the only method Meteor uses to determine how it should connect to the database.

**Comment by codeHatcher** [comment]
@rwatts3 your mongodb definitely has a port associated with it. Are you using docker to host your mongodb? are you using an entirely separate server? You should give us more details

**Comment by rwatts3** [comment]
Separate server. With. Nginx proxy so my mongo port is not the default for
security and infrastructure reasons.

**Comment by codeHatcher** [comment]
Makes sense, but I would assume it's still running on a specific port. You could enter your mongo shell if you have access to that and do https://docs.mongodb.com/manual/reference/command/getCmdLineOpts/

or maybe check via lsof

**Comment by Ulexus** [comment]
Closing this old issue; please reopen if it is still a problem.
