### ISSUE TITLE
settings.xml

### ISSUE THREAD

**Issue by Antoine-O** [CyCoreSystems/docker-meteor#25]
Hello ! 
Do you have a way to pass settings.xml ?

thanks :)

**Comment by Ulexus** [comment]
I don't, as it has never fit into my workflow, but I can see its utility.  Meteor can read the settings in from the `METEOR_SETTINGS` environment variable, so as far as I can see, we should be able to load the contexts of an arbitrary file into that environment variable to have it work.

I'm happy to take a PR for this.

**Comment by Ulexus** [comment]
I have added (to the v1.4 tag) support for `SETTINGS_FILE` and `SETTINGS_URL`, which attempt to load `settings.json` from a file or URL, respectively.  I can't speak to XML support; I would not have presumed Meteor had anything XML-related, but whatever is in one of these sources is loaded into the `METEOR_SETTINGS` environment variable.  Both are, by default, empty.

Example uses might be:

```
docker run -e SETTINGS_FILE=/data/config/app.json -v /data/config:/data/config ulexus/meteor:v1.4
```

```
docker run -e SETTINGS_URL=http://datasvr.mydomain.com/assets/app/settings.json ulexus/meteor:v1.4
```

**Comment by Antoine-O** [comment]
Sorry, mistyped for xml. Doing java and meteor may have cause this error 😀
Thanks!

**Comment by Antoine-O** [comment]
hey there !

I has to add 

export METEOR_SETTINGS

just before nodes server launch otherwise the settings.json are not taking into account. 

:)

**Comment by Ulexus** [comment]
Thanks @Antoine-O ; I have updated the entrypoint.sh to export `METEOR_SETTINGS` if it is set.

**Comment by T-Grave** [comment]
@Ulexus Any chance this change might find it's way into the legacy image?

**Comment by Ulexus** [comment]
That sounds reasonable; I'll take a look at it when I return next week.
