### ISSUE TITLE
npm install before meteor build

### ISSUE THREAD

**Issue by athyuttamre** [CyCoreSystems/docker-meteor#26]
If a Meteor app has npm dependencies listed in `package.json`, we need to run `npm install` (or perhaps `npm install --production`) before building the bundle.

Per this [guide section](https://guide.meteor.com/deployment.html#custom-deployment):

> Any npm dependencies must be installed before issuing the meteor build command to be included in the bundle.

Could you add a line to install npm dependencies before building the app?

**Comment by Ulexus** [comment]
Added; docker hub image updated.  Let me know if this works for you.  I do not use this feature.

**Comment by athyuttamre** [comment]
I'm not able to test anytime soon, but the commit looks good to me. If you wanted to be careful, you could do `meteor npm install --production` so the Node version matches the version that Meteor is using.
