### ISSUE TITLE
No Exposed Port

### ISSUE THREAD

**Issue by codeHatcher** [CyCoreSystems/docker-meteor#29]
I'm not seeing an exposed port

![pasted_image_9_23_16__9_10_am](https://cloud.githubusercontent.com/assets/5360982/18792985/9fb31e3a-816d-11e6-8736-76a69ada2e8e.png)

I'm using the following for the deploy
```bash
docker run --link mongodb:mongo --rm -e RELEASE=1.4.1 -e PORT=80 -e ROOT_URL=http://55.55.84.25 -e REPO=git@github.com:codeHatcher/autoDashboardGenerator.git -e DEPLOY_KEY=/root/.ssh/id_rsa -v /root/.ssh/id_rsa:/root/.ssh/id_rsa -e BRANCH=feature/moveAppDir -e MONGO_URL=mongodb://mongo:27017/app ulexus/meteor:v1.4-build
```

**Comment by codeHatcher** [comment]
![pasted_image_9_22_16__10_26_pm](https://cloud.githubusercontent.com/assets/5360982/18775028/b368dc3a-8113-11e6-815b-a317ef1b61b0.png)

**Comment by Ulexus** [comment]
That is correct; Docker does not expose ports on its own.  You have to tell it to expose a port, on execution with the `-p` option to `docker run`.  An example, in this case, would be `-p 80:80`.

**Comment by codeHatcher** [comment]
That worked, and everything else is up and running. Wohoo! Thanks!!

**Comment by harishreddy-m** [comment]
please mention this README
