### ISSUE TITLE
Meteor  "Retrying download in 5 seconds..."

### ISSUE THREAD

**Issue by Antoine-O** [CyCoreSystems/docker-meteor#30]
Hello there !

I can't dl Meteor during the docker "run" phase but I am able to do it in the docker "build" phase :/

```
Downloading Meteor install script...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7786    0  7786    0     0  17008      0 --:--:-- --:--:-- --:--:-- 17037
...talling Meteor 1.4.1.1
Downloading Meteor distribution
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...

```

any clues ?

**Comment by Ulexus** [comment]
I would suspect you have some problem with the network.  I have definitely seen individual launches which failed to download; cancelling and re-running the container has always worked.  The Meteor distribution is fairly large, so if your internet connection is not very good, that could be a problem.

**Comment by Antoine-O** [comment]
I have set the download of the meteor in the Dockerfile, and it fix it.
