### ISSUE TITLE
/usr/bin/entrypoint.sh: line 113:    54 Killed                  meteor build --directory ${APP_DIR}

### ISSUE THREAD

**Issue by sweetcharity** [CyCoreSystems/docker-meteor#31]
docker create -e ROOT_URL=http://test.com -e PORT=80 -e MONGO_URL=mongodb://mongo:27017/   -v /root/mu:/src/app --link mongo:mongo --name met ulexus/meteor:v1.4

docker start -i met
Meteor source found in /src/app/.meteor
Checking Meteor version...
1.4.1
Downloading Meteor install script...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7786    0  7786    0     0   2010      0 --:--:--  0:00:03 --:--:--  2010
Installing Meteor 1.4.1.1...
Removing your existing Meteor installation.
Downloading Meteor distribution

Meteor 1.4.1.1 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com

Installing application-side NPM dependencies...
Building the bundle...(this may take a while)
/usr/bin/entrypoint.sh: line 113:    54 Killed                  meteor build --directory ${APP_DIR}

what's wrong?

**Comment by Ulexus** [comment]
Most likely, your container is being killed for being out of RAM.  If you check `dmesg`, you should see that the out of memory killer killed it.

**Comment by sweetcharity** [comment]
yep, it's node
[86739.353788] Out of memory: Kill process 1469 (node) score 670 or sacrifice child
[86739.353876] Killed process 1469 (node) total-vm:1927084kB, anon-rss:676160kB, file-rss:0kB

I'll try to add more RAM

**Comment by sweetcharity** [comment]
it's ok now, thanks
