### ISSUE TITLE
compile/bundle meteor app with dockerfile

### ISSUE THREAD

**Issue by Antoine-O** [CyCoreSystems/docker-meteor#32]
hey there,

is there any way to compile meteor app in the dockerfile, the compilation is so long while deploying :/

thanks.

**Comment by Ulexus** [comment]
Yes.  I do exactly that.  Take a look at the [example](https://github.com/CyCoreSystems/docker-meteor/tree/v1.4/examples).

**Comment by Ulexus** [comment]
You needn't use the kubernetes part; the first part of the deploy script is all you need, with the `Dockerfile`.  Basically, something like this:

```bash
cd $app_source
meteor build --directory /tmp/export-meteor/build
cat >/tmp/export-meteor/Dockerfile <<ENDHERE
FROM ulexus/meteor:v1.4
COPY build /var/www
ENDHERE
cd /tmp/export-meteor
docker build -t myapp .
docker push myapp
```
