### ISSUE TITLE
npm install never finishes on run

### ISSUE THREAD

**Issue by jshimko** [CyCoreSystems/docker-meteor#4]
Hey there.  I've tried a bunch of different Meteor app repos and I keep getting stopped up the same point in the run process.

I run:
```bash
docker run --rm \
  -e ROOT_URL=http://DOCKER_HOST_IP \
  -e REPO=https://github.com/meteor/simple-todos.git \
  -e BRANCH=master \
  -e MONGO_URL=mongodb://NAME:PW@URL:PORT/DB \
  ulexus/meteor
```

Then I get here the following and it hangs indefinitely.

```
Getting https://github.com/meteor/simple-todos.git...
Cloning into '/usr/src/app'...
Switching to branch/tag master...
Already on 'master'
Your branch is up-to-date with 'origin/master'.
/var/www/bundle/programs/server /usr/src/app
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

> fibers@1.0.1 install /var/www/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
progress@1.1.8 node_modules/progress

ip@0.3.2 node_modules/ip

underscore@1.5.2 node_modules/underscore

semver@2.2.1 node_modules/semver

chalk@0.5.1 node_modules/chalk
├── escape-string-regexp@1.0.2
├── ansi-styles@1.1.0
├── supports-color@0.2.0
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)

source-map-support@0.2.5 node_modules/source-map-support
└── source-map@0.1.29 (amdefine@0.1.0)

fibers@1.0.1 node_modules/fibers
/usr/src/app
```

For what it's worth, I can successfully deploy with Arunoda's [MeteorD][1] with the exact same repo and database url, so it's definitely not the code or the env vars.  His package gets the job done, but I'd really prefer the convenience of deploying from a github repo instead of having to Dockerize every app I want to deploy.

Any suggestions on what I may be missing here?  Thanks in advance!  

[1]: https://registry.hub.docker.com/u/meteorhacks/meteord/

**Comment by Ulexus** [comment]
That log looks completely normal.  It should be running at that point.  You are missing the PORT environment variable, though.  It will default to port 80, but you don't have a port forward statement in your `docker run` either.  That means it should be running on port 80 of the _container_, but in the default docker environment, that won't do you much good.

Try adding a `-p 80:80` switch to your `docker run` statement.

**Comment by jshimko** [comment]
Oops.  It's always the obvious thing starring you in the face!  :)

Thanks for the quick reply.
