### ISSUE TITLE
Application's Meteor version (1.5) is less than 1.3.1; please use ulexus/meteor:legacy

### ISSUE THREAD

**Issue by kaihendry** [CyCoreSystems/docker-meteor#51]
Building with REPO=https://github.com/unee-t/unee-t-fe

**Comment by Ulexus** [comment]
The semver package we use is lousy.  It can't figure out what `x.y` versions are.  Can you upgrade to 1.5.1?

**Comment by kaihendry** [comment]
Ok, I've flagged it out of date https://aur.archlinux.org/packages/meteor-js/
