### ISSUE TITLE
meteor build --debug

### ISSUE THREAD

**Issue by kaihendry** [CyCoreSystems/docker-meteor#53]
Is it possible to do a debug build from a git repo?

**Comment by Ulexus** [comment]
To be consistent with the [docs](https://docs.meteor.com/commandline.html), I have added the variable `NODE_OPTIONS`, which will be passed to node on execution.  To enable debug, you can set the environment variable accordingly:

```
NODE_OPTIONS='--debug'
```

4f786b078b84f23d81d924272f18db3a72702db7
