### ISSUE TITLE
Struggling to get this running in SRC mode on OSX

### ISSUE THREAD

**Issue by adamgins** [CyCoreSystems/docker-meteor#54]
Thanks for this image and info

I am trying to run a simple test on my dev machine (OSX) 

My meteor project is located in `/Users/myusername/Documents/development/proj1`

`docker run --rm -e ROOT_URL=https://somengrokXYZ123.ngrok.io -p 80:80 -v /Users/myusername/Documents/development/proj1   ulexus/meteor`

I get error `Unable to locate server directory in ; hold on: we're likely to fail
Failed to locate main.js in ; cannot start application.`

Seems similar to https://github.com/CyCoreSystems/docker-meteor/issues/19

I have tried with settings file etc etc.. still get same issue. 

Any help appreciated.

thanks

**Comment by Ulexus** [comment]
You need to specify both sides of that volume.  That is, mount the source to `/home/meteor/src` in the container with something like `-v /Users/myusername/Documents/development/proj1:/home/meteor/src`.
