### ISSUE TITLE
Trying to use meteor 1.6

### ISSUE THREAD

**Issue by greggman** [CyCoreSystems/docker-meteor#56]
I tried using meteor 1.6 with

     RELEASE=1.6

And got this message:

    Application's Meteor version (1.6) is less than 1.3.1; please use ulexus/meteor:legacy

I'm guessing it wants me to put in 1.6.0? or 1.6.0.0 but meteor itself, after upgrading from 1.5.2.2 just says 1.6 when using `meteor version`

another issue seems to be the node version. This container references node 4 but meteor 1.6 seems to need node 8

**Comment by Ulexus** [comment]
You are correct; this is an unfortunate problem in the `semver` package we are using.  I really need to figure out some way to replace or work around that problem.

**Comment by Ulexus** [comment]
Fixed by 73241f38dff8bc6b1af586f81e4b112e139d7648

**Comment by Ulexus** [comment]
Fix not sufficient... back to the drawing board.

**Comment by smeijer** [comment]
Another problem with the 1.6 release, is that it requires a newer version of Node. Perhaps make the NODE version configurable? Or extract it from `meteor node -v`?

**Comment by Ulexus** [comment]
@smeijer That's a good idea.  Are you up to writing it?  In any case, please do create a new issue about it.
