### ISSUE TITLE
MongoDB connection documentation needs help

### ISSUE THREAD

**Issue by Ulexus** [CyCoreSystems/docker-meteor#7]
@keyscores :  "There are different env variables for mongo. So just need examples for
using each. I haven't yet managed to get my app to run with this docker
image, while a mongo instance runs on the same host."

**Comment by Ulexus** [comment]
This is better documented, now.

**Comment by keyscores** [comment]
@Ulexus  thanks. BTW how does Git authentication work? For private repos...

**Comment by Ulexus** [comment]
@keyscores Set the `DEPLOY_KEY` environment variable to the path of the private key for your SSH authentication.  The path should be from the point of view of the container.  The systemd unit file example has this setup.
