### ISSUE TITLE
Mounting volume with APP_DIR

### ISSUE THREAD

**Issue by xloup** [CyCoreSystems/docker-meteor#8]
when I use:  -e APP_DIR=/home/myUser/mymetorFolder

I get a message :    
 Unable to locate server directory; hold on: we're likely to fail
/usr/bin/entrypoint.sh: line 101: cd: /home/myUser/mymetorFolder: No such file or directory

This folder does exist ... and I have no permissions problem on mounting volumes with other containers from that folder...

**Comment by xloup** [comment]
I am probably not doing this right, since dockerfile seems will need to be changed as per bellow readme comment: 
Bind-mount, volume, Dockerfile ADD via environment variable (APP_DIR)

**Comment by Ulexus** [comment]
Correct; if you are trying to reference a directory external of the container, you will need to bind-mount that directory into place.  In your case, you would want to execute the command with something like this:
```
docker run -e APP_DIR=/app -v /home/myUser/mymetorFolder:/app [additional options] ulexus/meteor
```

**Comment by xloup** [comment]
Thanks that works great !

Thank you also for taking the time to answer
